from .triplet_loss import TripletLoss
from .supcontrast import SupConLoss
from .cross_modal_triplet_loss import CrossModalTripletLoss
from .cross_modal_triplet_loss_sum import SumConstraintCrossModalTripletLoss